// AUTO-GENERATED by scripts/gen-license-keys.mjs. Public key only, safe to commit.
// The extension verifies Pro licenses against this, fully offline.
window.AIRLOCK_LICENSE_PUBKEY = "fNe-pqC2fQWLKPPGw05pHSrH4k8pViOhqGukgbkG4II"
